name: sac-beta
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - ca-certificates=2022.10.11
  - certifi=2022.9.24
  - openssl=1.1.1s
  - pip=22.2.2
  - python=3.10.2
  - setuptools=65.5.0
  - sqlite=3.39.3
  - tk=8.6.12
  - typing_extensions=4.3.0
  - wheel=0.37.1
  - xz=5.2.6
  - zlib=1.2.13
  - pip:
    - absl_py==1.4.0
    - astunparse==1.6.3
    - bitmath==1.3.3.1
    - black==23.3.0
    - cachetools==5.3.0
    - certifi==2022.12.7
    - chardet==4.0.0
    - charset_normalizer==3.1.0
    - click==8.1.3
    - cloudpickle==2.2.1
    - contourpy==1.0.7
    - cycler==0.11.0
    - decorator==5.1.1
    - dill==0.3.6
    - dm_env==1.6
    - dm_tree==0.1.7
    - enum-tools==0.9.0.post1
    - envpool==0.8.1
    - Farama_Notifications==0.0.4
    - flatbuffers==22.9.24
    - fonttools==4.39.3
    - gast==0.4.0
    - google-auth==2.17.2
    - google-pasta==0.2.0
    - google_auth_oauthlib==0.4.6
    - graphviz==0.20.1
    - grpcio==1.51.3
    - gym==0.26.2
    - gym_notices==0.0.8
    - gymnasium==0.28.1
    - h5py==3.8.0
    - hbutils==0.8.2
    - idna==3.4
    - isort==5.12.0
    - jax_jumpy==1.0.0
    - keras==2.11.0
    - kiwisolver==1.4.4
    - libclang==14.0.1
    - llvmlite==0.39.1
    - Markdown==3.4.3
    - MarkupSafe==2.1.2
    - matplotlib==3.7.0
    - mypy-extensions==1.0.0
    - numba==0.56.3
    - numpy==1.23.2
    - oauthlib==3.2.2
    - opt_einsum==3.3.0
    - packaging==23.0
    - pathspec==0.11.1
    - Pillow==9.5.0
    - platformdirs==3.2.0
    - protobuf==3.19.6
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - Pygments==2.14.0
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pytimeparse==1.1.8
    - requests==2.28.2
    - requests_oauthlib==1.3.1
    - rsa==4.9
    - six==1.16.0
    - tensorboard==2.11.2
    - tensorboard-data-server==0.6.1
    - tensorboard_plugin_wit==1.8.1
    - tensorflow==2.11.0
    - tensorflow_estimator==2.11.0
    - tensorflow_io_gcs_filesystem==0.26.0
    - tensorflow_probability==0.19.0
    - termcolor==2.2.0
    - tianshou==0.5.0
    - tomli==2.0.1
    - torch==1.13.1
    - tqdm==4.65.0
    - treevalue==1.4.10
    - types-protobuf==4.22.0.2
    - typing_extensions==4.5.0
    - urllib3==1.26.15
    - Werkzeug==2.2.3
    - wrapt==1.15.0
