name: sac-beta
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - _libgcc_mutex=0.1
  - ca-certificates=2022.10.11
  - certifi=2022.9.24
  - openssl=1.1.1s
  - pip=22.2.2
  - python=3.8.13
  - setuptools=65.5.0
  - sqlite=3.39.3
  - tk=8.6.12
  - typing_extensions=4.3.0
  - wheel=0.37.1
  - xz=5.2.6
  - zlib=1.2.13
  - pip:
    - absl-py==1.4.0
    - astunparse==1.6.3
    - black==23.3.0
    - cachetools==5.3.0
    - charset-normalizer==3.1.0
    - click==8.1.3
    - cloudpickle==2.2.1
    - cmake==3.26.1
    - contourpy==1.0.7
    - cycler==0.11.0
    - decorator==5.1.1
    - dm-env==1.6
    - dm-tree==0.1.8
    - envpool==0.8.2
    - farama-notifications==0.0.4
    - filelock==3.10.7
    - flatbuffers==23.3.3
    - fonttools==4.39.3
    - gast==0.4.0
    - glfw==2.5.9
    - google-auth==2.17.1
    - google-auth-oauthlib==1.0.0
    - google-pasta==0.2.0
    - grpcio==1.53.0
    - gym==0.26.2
    - gym-notices==0.0.8
    - gymnasium==0.28.1
    - h5py==3.8.0
    - idna==3.4
    - imageio==2.27.0
    - importlib-metadata==6.1.0
    - importlib-resources==5.12.0
    - isort==5.12.0
    - jax==0.4.8
    - jax-jumpy==1.0.0
    - jinja2==3.1.2
    - keras==2.12.0
    - kiwisolver==1.4.4
    - libclang==16.0.0
    - lit==16.0.0
    - llvmlite==0.39.1
    - markdown==3.4.3
    - markupsafe==2.1.2
    - matplotlib==3.7.1
    - ml-dtypes==0.0.4
    - mpmath==1.3.0
    - mujoco==2.3.3
    - mypy-extensions==1.0.0
    - networkx==3.0
    - numba==0.56.4
    - numpy==1.23.5
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nvtx-cu11==11.7.91
    - oauthlib==3.2.2
    - opt-einsum==3.3.0
    - optree==0.9.0
    - packaging==23.0
    - pathspec==0.11.1
    - pillow==9.5.0
    - platformdirs==3.2.0
    - protobuf==4.22.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pygame==2.1.3
    - pyopengl==3.1.6
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - requests==2.28.2
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - scipy==1.10.1
    - six==1.16.0
    - swig==4.1.1
    - sympy==1.11.1
    - tabulate==0.9.0
    - tensorboard==2.12.1
    - tensorboard-data-server==0.7.0
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.12.0
    - tensorflow-estimator==2.12.0
    - tensorflow-io-gcs-filesystem==0.32.0
    - tensorflow-probability==0.19.0
    - termcolor==2.2.0
    - tianshou==0.5.0
    - tomli==2.0.1
    - torch==2.0.0
    - tqdm==4.65.0
    - triton==2.0.0
    - types-protobuf==4.22.0.0
    - urllib3==1.26.15
    - werkzeug==2.2.3
    - wrapt==1.14.1
    - zipp==3.15.0
